inc = float(input())
ex = float(input())
print("1234567890" * 3)
print("Total Income {:+8.2f} bahts".format(inc))
print("Expense      {:8.2f} bahts".format(ex))
print("Profit       {:008.2f} bahts".format(inc+ex))